### ISSUE TITLE
KeyError: 'REPLIT_DB_URL'

### ISSUE THREAD

**Issue by stjet** [Codemonkey51/replit-db-client#1]
![image](https://user-images.githubusercontent.com/49297268/85807483-e3566c00-b706-11ea-8938-7778dcff1620.png)
![image](https://user-images.githubusercontent.com/49297268/85807536-100a8380-b707-11ea-9881-fc399485701e.png)

https://repl.it/@rediar/Chess-Online-Expiremental#db.py

**Comment by PotentialStyx** [comment]
I'll see I think this may be an issue with repl

**Comment by PotentialStyx** [comment]
I have not seen this anymore and at this point it has to be an issue with repl if it happens (it just is checking env vars rn)

**Comment by stjet** [comment]
I think you can close this, seems like it works now...

**Comment by PotentialStyx** [comment]
Okay
