### ISSUE TITLE
Can't use nested dictionaries

### ISSUE THREAD

**Issue by adl212** [Codemonkey51/replit-db-client#8]
Can't add nested dictionaries to the replit database.

**Comment by PotentialStyx** [comment]
Sorry about that I'm going to fix this bc it's sending it as data so it needs to be a str so I'll make it auto convert you'll need to import json and use json.loads(client.view(<name>)) to get the json but it I don't encode everything as strs it will break

**Comment by adl212** [comment]
When I do `json.loads(client.view())` with the key name as the argument, it still doesn't work.

**Comment by PotentialStyx** [comment]
yes bc rn it passes exactly what you sent im going to make it stringify it first now

**Comment by PotentialStyx** [comment]
has been fixed in 0.0.13 (no longer use json.loads it auto does that)

**Comment by PotentialStyx** [comment]
make sure to update the package tho (on repl remove  and then add the package in the package tab)

**Comment by PotentialStyx** [comment]
that version broke ill try to fix (and was yanked)

**Comment by PotentialStyx** [comment]
release should be fixed

**Comment by PotentialStyx** [comment]
error has not been fixed miscall

**Comment by PotentialStyx** [comment]
finally been fixed lol

**Comment by PotentialStyx** [comment]
make sure your on 0.0.13.3

**Comment by adl212** [comment]
Ok, so fixed.
